function Language() {
    this.locales = {
        "de_DE": "Deutsch",
        "en_US": "English",
        "bg_BG": "?????????",
        "es_ES": "espanol",
        "uk_UA": "??????????",
        "ru_RU": "???????",
    };

    this.languages = {
        "de_DE": {
            "ECP_ADDMACHINE": "Automat hinzuf�gen",
            "ECP_ADDMACHINEDIALOGUEINFORMATION": "Bitte eine Beschreibung f�r den Automaten eingeben:",
            "ECP_CANCELBUTTON": "Abbrechen",
            "ECP_CLEARLOG": "Log l�schen",
            "ECP_CLOCKSPERSECONDUNIT": "Hz",
            "ECP_CLOSEBUTTON": "Schlie�en",
            "ECP_CONNECT": "Verbinden",
            "ECP_CONNECTING": "Verbinde",
            "ECP_CONNECTIONREMAININGTIME": "Verbleibende Zeit",
            "ECP_CONNECTIONTOTALTIME": "Verbindungsdauer",
            "ECP_CONTROLHEADER": "Bedienelemente",
            "ECP_CURRENTINPUTVALUE": "Momentane Eingangsbelegung",
            "ECP_CURRENTSTATE": "Momentaner Zustand",
            "ECP_DELETEALLBUTTON": "Alles l�schen",
            "ECP_DELETEMACHINE": "Automat l�schen",
            "ECP_DELETEMACHINEDIALOGUEINFORMATION": "Sind sie sicher?",
            "ECP_DISCONNECT": "Trennen",
            "ECP_DISCONNECTED": "Getrennt",
            "ECP_DISCONNECTEDMESSAGE": "Verbindung wurde getrennt. Bitte schlie�en Sie das Browserfenster!",
            "ECP_EQUATIONDEFINER": ":=",
            "ECP_EQUATIONSTABSINPUTS": "",
            "ECP_EQUATIONTABSHEADER": "Eingabe von Steuergleichungen",
            "ECP_EQUATIONTABSHSTAR": "h*",
            "ECP_EQUATIONTABSMACHINES": "Automaten",
            "ECP_EQUATIONTABSOUTPUTS": "Ausg�nge y",
            "ECP_ERRORLOG": "Fehlerlog",
            "ECP_EXAMPLEBUTTON": "Beispiel",
            "ECP_FILETRANSFERCOMPLETE": "Datentransfer abgeschlossen",
            "ECP_INITIALIZE": "Initialisieren",
            "ECP_INITIALMODELSTATE": "Modellzustand",
            "ECP_INITSTATE": "Initialzustand",
            "ECP_INPUTDESCRIPTION": "Beschreibung der IOs",
            "ECP_LANGUAGES": "Sprachen",
            "ECP_NAME": "Deutsch",
            "ECP_NOFILESELECTED": "Keine Datei ausgew�hlt",
            "ECP_OKBUTTON": "OK",
            "ECP_ONLYSIMULATE": "Nur simulieren",
            "ECP_OPENBUTTON": "�ffnen",
            "ECP_OPTIONSBUTTON": "Optionen",
            "ECP_RESETSIMULATION": "Reset",
            "ECP_SAVEBUTTON": "Speichern",
            "ECP_SAVEBUTTONLABEL": "Speichern",
            "ECP_SCENARIOEDITORDESCRIPTION": "Initialzustand des Modells:",
            "ECP_SENSORDISTANCEUNIT": "Takte",
            "ECP_SIMULATIONCLOCKSLIDER": "Frequenz",
            "ECP_SIMULATIONSENSORSLIDER": "Sensorabstand",
            "ECP_START": "Start",
            "ECP_STOP": "Stopp",
            "ECP_WEBCAMENABLED": "Webcam aktivieren",
            "ECP_ZEQUATIONS": "z-Gleichungen",
            "ERROR_LAB_0": "Falsche Session ID.",
            "ERROR_LAB_1": "GoldiAPI ist nicht verbunden.",
            "ERROR_LAB_10": "BPU konnte nicht resetet werden.",
            "ERROR_LAB_11": "BPU Zieladresse setzen f�r PSPU nicht erfolgreich.",
            "ERROR_LAB_12": "BPU Programming: Dateiformat nicht unterst�tzt",
            "ERROR_LAB_13": "BPU Programming: Dateiformat Parse-Fehler",
            "ERROR_LAB_14": "BPU Programming: Fehler",
            "ERROR_LAB_15": "PSPU ist nicht erreichbar.",
            "ERROR_LAB_16": "PSPU konnte nicht resetet werden.",
            "ERROR_LAB_17": "PSPU Zieladresse setzen f�r PSPU nicht erfolgreich.",
            "ERROR_LAB_18": "PSPU Experiment starten ist fehlgeschlagen.",
            "ERROR_LAB_19": "PSPU Experiment initialisieren ist fehlgeschlagen.",
            "ERROR_LAB_2": "GoldiAPI: kein g�ltiges Kommando.",
            "ERROR_LAB_20": "PSPU Experiment initialisieren ist fehlgeschlagen.",
            "ERROR_LAB_21": "PSPU Experiment initialisieren ist fehlgeschlagen.",
            "ERROR_LAB_22": "Zeit�berschreitung bei letztem Kommando.",
            "ERROR_LAB_3": "BCU f�r BPU wurde nicht in der Datenbank gefunden.",
            "ERROR_LAB_4": "BCU f�r BPU ist nicht erreichbar.",
            "ERROR_LAB_5": "BCU Kanal f�r BPU konnte nicht gesetzt werden. Manueller Modus aktiviert?",
            "ERROR_LAB_6": "BCU f�r PSPU wurde nicht in der Datenbank gefunden.",
            "ERROR_LAB_7": "BCU f�r PSPU ist nicht erreichbar.",
            "ERROR_LAB_8": "BCU Kanal f�r PSPU konnte nicht gesetzt werden. Manueller Modus aktiviert?",
            "ERROR_LAB_9": "BPU ist nicht erreichbar.",
            "ERROR_PARSE_0": "Undefinierte Variable",
            "ERROR_PARSE_1": "Syntaxfehler in Gleichung",
            "ERROR_PARSE_10": "Undefinierter Zustand in Automat",
            "ERROR_PARSE_11": "Die Anzahl der Zustandsvariablen pro Automat muss mindestens 1 betragen",
            "ERROR_PARSE_12": "Unbekannte Y-Variable",
            "ERROR_PARSE_2": "Fehler in der Variablenauswertung",
            "ERROR_PARSE_23": "Automat nicht definiert",
            "ERROR_PARSE_24": "Unbekannter Automat",
            "ERROR_PARSE_25": "Nur ein Zeichen f�r Variablennamen erlaubt",
            "ERROR_PARSE_26": "Fehlerhafte Datei",
            "ERROR_PARSE_3": "Klammerfehler in Gleichung",
            "ERROR_PARSE_4": "Unbekanntes Zeichen in Gleichung",
            "ERROR_PARSE_5": "Zu viele Eingabevariablen �bergeben",
            "ERROR_PARSE_6": "Zu wenige Eingabevariablen �bergeben",
            "ERROR_PARSE_7": "H* ist wahr",
            "ERROR_PARSE_8": "Undefinierte Gleichung y:",
            "ERROR_PARSE_9": "Zustandsvariable existiert nicht:",
            "ERROR_SIDAC_0": "Ung�ltige Simulationsfrequenz gew�hlt",
            "ERROR_SIDAC_1": "Sensordistanz kann nicht unter 1 betragen",
            "ERROR_SIDAC_10": "F�rderband 1 schon belegt",
            "ERROR_SIDAC_11": "F�rderband 1 aktiv und Drehtisch 1 nicht nach F�rderband 1 ausgerichtet",
            "ERROR_SIDAC_12": "Drehtisch 1 schon belegt",
            "ERROR_SIDAC_13": "Kann Drehtisch 1 nicht f�rdern lassen, da sonst ein Werkst�ck herunter f�llt",
            "ERROR_SIDAC_14": "Kann Drehtisch 1 nicht drehen, da sich ein Werkst�ck zwischen F�rderband 1 und Drehtisch 1 befindet",
            "ERROR_SIDAC_15": "Kann Drehtisch 1 nicht nach F�rderband 2 drehen, da er schon nach F�rderband 2 ausgerichtet ist",
            "ERROR_SIDAC_16": "Kann Drehtisch 1 nicht nach F�rderband 1 drehen, da er schon nach F�rderband 1 ausgerichtet ist",
            "ERROR_SIDAC_17": "Kann Drehtisch 1 nicht drehen, da sich ein Werkst�ck zwischen Drehtisch 1 und F�rderband 2 befindet",
            "ERROR_SIDAC_18": "Kann Drehtisch 1 nicht in beide Richtungen gleichzeitig drehen",
            "ERROR_SIDAC_19": "F�rderband 2 schon belegt",
            "ERROR_SIDAC_2": "Undefinierter Ausgabewert",
            "ERROR_SIDAC_20": "F�rderband 2 aktiv und Drehtisch 2 nicht nach F�rderband 2 ausgerichtet",
            "ERROR_SIDAC_21": "Drehtisch 2 schon belegt",
            "ERROR_SIDAC_22": "Kann Drehtisch 2 nicht f�rdern lassen, da sonst ein Werkst�ck herunter f�llt",
            "ERROR_SIDAC_23": "Kann Drehtisch 2 nicht drehen, da sich ein Werkst�ck zwischen F�rderband 2 und Drehtisch 2 befindet",
            "ERROR_SIDAC_24": "Kann Drehtisch 2 nicht nach F�rderband 3 drehen, da er schon nach F�rderband 3 ausgerichtet ist",
            "ERROR_SIDAC_25": "Kann Drehtisch 2 nicht drehen, da sich ein Werkst�ck zwischen Drehtisch 2 und F�rderband 3 befindet",
            "ERROR_SIDAC_26": "Kann Drehtisch 2 nicht nach F�rderband 2 drehen, da er schon nach F�rderband 2 ausgerichtet ist",
            "ERROR_SIDAC_27": "Kann Drehtisch 2 nicht in beide Richtungen gleichzeitig drehen",
            "ERROR_SIDAC_28": "F�rderband 3 schon belegt",
            "ERROR_SIDAC_29": "Kann F�rderband 3 nicht f�rdern lassen, da sonst ein Werkst�ck herunter f�llt",
            "ERROR_SIDAC_3": "Transporttisch schon an F�rderband 3",
            "ERROR_SIDAC_30": "Transporttisch schon belegt",
            "ERROR_SIDAC_31": "Kann Fr�smaschine nicht zu F�rderband 2 fahren, da diese schon an F�rderband 2 ist",
            "ERROR_SIDAC_32": "Kann Fr�smaschine nicht in beide Richtungen gleichzeitig fahren",
            "ERROR_SIDAC_33": "Kann Fr�smaschine nicht weiter von F�rderband 2 entfernen",
            "ERROR_SIDAC_34": "Kann Fr�skopf nicht weiter heben",
            "ERROR_SIDAC_35": "Kann Fr�skopf nicht in beide Richtungen gleichzeitig bewegen",
            "ERROR_SIDAC_36": "Kann Fr�skopf nicht weiter senken",
            "ERROR_SIDAC_4": "Kann Transporttisch nicht nach F�rderband 3 bewegen da sich ein Werkst�ck zwischen dem Transporttisch und F�rderband 1 befindet",
            "ERROR_SIDAC_5": "Transporttisch kann nicht gleichzeitig in beide Richtungen bewegen",
            "ERROR_SIDAC_6": "Transporttisch schon an F�rderband 1",
            "ERROR_SIDAC_7": "Kann Transporttisch nicht nach F�rderband 1 bewegen da sich ein Werkst�ck zwischen dem Transporttisch und F�rderband 3 befindet",
            "ERROR_SIDAC_8": "Kann F�rderband auf Transporttisch nicht betreiben, da sonst ein Werkst�ck herunter f�llt",
            "ERROR_SIDAC_9": "Kann Transporttisch nicht nach F�rderband 1 f�rdern lassen, da er sich nicht an F�rderband 1 befindet",
            "SIDAC_ANIMATION_CB1": "FB1",
            "SIDAC_ANIMATION_CB2": "FB2",
            "SIDAC_ANIMATION_CB3": "FB3",
            "SIDAC_ANIMATION_RT1": "DT1",
            "SIDAC_ANIMATION_RT2": "DT2",
            "SIDAC_ANIMATION_TT": "TT",
            "INPUTS_X0": "Transprottisch in Richtung F�rderband 3 (Low-Aktiv)",
            "INPUTS_X1": "Transporttisch in Richtung F�rderband 1 (Low-Aktiv)",
            "INPUTS_X10": "Drehtisch 2 - Werkst�ck vorhanden",
            "INPUTS_X11": "F�rderband 3 - Werkst�ck vorhanden",
            "INPUTS_X12": "Werkzeugmaschine von F�rderband 2 entfernt (Low-Aktiv)",
            "INPUTS_X13": "Werkzeugmaschine an F�rderband 2 (Low-Aktiv)",
            "INPUTS_X14": "Fr�se ist oben (Low-Aktiv)",
            "INPUTS_X15": "Fr�se ist unten (Low-Aktiv)",
            "INPUTS_X16": "Notaus",
            "INPUTS_X2": "Transporttisch 1 - Werkst�ck vorhanden",
            "INPUTS_X3": "F�rderband 1 - Werkst�ck vorhanden",
            "INPUTS_X4": "Drehtisch 1 in Richtung F�rderband 1 (Low-Aktiv)",
            "INPUTS_X5": "Drehtisch 1 in Richtung F�rderband 2 (Low-Aktiv)",
            "INPUTS_X6": "Drehtisch 1 - Werkst�ck vorhanden",
            "INPUTS_X7": "F�rderband 2 - Werkst�ck vorhanden",
            "INPUTS_X8": "Drehtisch 2 in Richtung F�rderband 2 (Low-Aktiv)",
            "INPUTS_X9": "Drehtisch 2 in Richtung F�rderband 3 (Low-Aktiv)",
            "SIDAC_LOG_0": "",
            "SIDAC_LOG_1": "",
            "OUTPUTS_Y0": "Transporttisch - fahren in Richtung F�rderband 3",
            "OUTPUTS_Y1": "Transporttisch - fahren in Richtung F�rderband 1",
            "OUTPUTS_Y10": "Drehtisch 2 - Nach F�rderband 3 drehen",
            "OUTPUTS_Y11": "Drehtisch 2 - F�rdern",
            "OUTPUTS_Y12": "F�rderband 3 - F�rdern",
            "OUTPUTS_Y13": "Werkzeugmaschine - entfernen von F�rderband 2",
            "OUTPUTS_Y14": "Werkzeugmaschine - nach F�rderband 2 fahren",
            "OUTPUTS_Y15": "Werkzeugmaschine - heben",
            "OUTPUTS_Y16": "Werkzeugmaschine - senken",
            "OUTPUTS_Y17": "Werkzeugmaschine - fr�sen",
            "OUTPUTS_Y2": "Transporttisch - f�rdern in Laufrichtung wie F�rderband 1",
            "OUTPUTS_Y3": "Transporttisch - f�rdern in Laufrichtung wie F�rderband 3 ",
            "OUTPUTS_Y4": "F�rderband 1 - f�rdern",
            "OUTPUTS_Y5": "Drehtisch 1 - nach F�rderband 1 drehen",
            "OUTPUTS_Y6": "Drehtisch 1 - nach F�rderband 2 drehen",
            "OUTPUTS_Y7": "Drehtisch 1 - f�rdern",
            "OUTPUTS_Y8": "F�erderband 2 - f�rdern",
            "OUTPUTS_Y9": "Drehtisch 2 - Nach F�rderband 2 drehen",
        },
        "en_US": {
            "ECP_ADDMACHINE": "Add machine",
            "ECP_ADDMACHINEDIALOGUEINFORMATION": "Please enter a description for the machine:",
            "ECP_CANCELBUTTON": "Cancel",
            "ECP_CLEARLOG": "Clear log",
            "ECP_CLOCKSPERSECONDUNIT": "Hz",
            "ECP_CLOSEBUTTON": "Close",
            "ECP_CONNECT": "Connect",
            "ECP_CONNECTING": "Connecting",
            "ECP_CONNECTIONREMAININGTIME": "Time remaining",
            "ECP_CONNECTIONTOTALTIME": "Connection duration",
            "ECP_CONTROLHEADER": "Controls",
            "ECP_CURRENTINPUTVALUE": "Current input value",
            "ECP_CURRENTSTATE": "Current state",
            "ECP_DELETEALLBUTTON": "Delete all",
            "ECP_DELETEMACHINE": "Delete machine",
            "ECP_DELETEMACHINEDIALOGUEINFORMATION": "Are you sure?",
            "ECP_DISCONNECT": "Disconnect",
            "ECP_DISCONNECTED": "Disconnected",
            "ECP_DISCONNECTEDMESSAGE": "Connection terminated. Please close your browser window!",
            "ECP_EQUATIONDEFINER": ":=",
            "ECP_EQUATIONSTABSINPUTS": "",
            "ECP_EQUATIONTABSHEADER": "Input Equations",
            "ECP_EQUATIONTABSHSTAR": "h*",
            "ECP_EQUATIONTABSMACHINES": "Machines",
            "ECP_EQUATIONTABSOUTPUTS": "Outputs y",
            "ECP_ERRORLOG": "Error log",
            "ECP_EXAMPLEBUTTON": "Example",
            "ECP_FILETRANSFERCOMPLETE": "File transfer complete",
            "ECP_INITIALIZE": "Initialize",
            "ECP_INITIALMODELSTATE": "Model state",
            "ECP_INITSTATE": "Initial state",
            "ECP_INPUTDESCRIPTION": "IO description",
            "ECP_LANGUAGES": "Languages",
            "ECP_NAME": "English",
            "ECP_NOFILESELECTED": "No file selected",
            "ECP_OKBUTTON": "OK",
            "ECP_ONLYSIMULATE": "Simulation only",
            "ECP_OPENBUTTON": "Open",
            "ECP_OPTIONSBUTTON": "Options",
            "ECP_RESETSIMULATION": "Reset",
            "ECP_SAVEBUTTON": "Save",
            "ECP_SAVEBUTTONLABEL": "Save",
            "ECP_SCENARIOEDITORDESCRIPTION": "Initial state of the Model:",
            "ECP_SENSORDISTANCEUNIT": "Clocks",
            "ECP_SIMULATIONCLOCKSLIDER": "Frequency",
            "ECP_SIMULATIONSENSORSLIDER": "Sensor distance",
            "ECP_START": "Start",
            "ECP_STOP": "Stop",
            "ECP_WEBCAMENABLED": "Enable webcam",
            "ECP_ZEQUATIONS": "z equations",
            "ERROR_LAB_0": "Wrong Session ID",
            "ERROR_LAB_1": "GoldiAPI not connected",
            "ERROR_LAB_10": "BPU could not be reset",
            "ERROR_LAB_11": "",
            "ERROR_LAB_12": "",
            "ERROR_LAB_13": "",
            "ERROR_LAB_14": "",
            "ERROR_LAB_15": "",
            "ERROR_LAB_16": "",
            "ERROR_LAB_17": "",
            "ERROR_LAB_18": "",
            "ERROR_LAB_19": "",
            "ERROR_LAB_2": "GoldiAPI: Invalid Command",
            "ERROR_LAB_20": "",
            "ERROR_LAB_21": "",
            "ERROR_LAB_22": "",
            "ERROR_LAB_3": "",
            "ERROR_LAB_4": "",
            "ERROR_LAB_5": "",
            "ERROR_LAB_6": "",
            "ERROR_LAB_7": "",
            "ERROR_LAB_8": "",
            "ERROR_LAB_9": "",
            "ERROR_PARSE_0": "Undefined variable",
            "ERROR_PARSE_1": "",
            "ERROR_PARSE_10": "",
            "ERROR_PARSE_11": "",
            "ERROR_PARSE_12": "",
            "ERROR_PARSE_2": "",
            "ERROR_PARSE_23": "",
            "ERROR_PARSE_24": "",
            "ERROR_PARSE_25": "",
            "ERROR_PARSE_26": "",
            "ERROR_PARSE_3": "",
            "ERROR_PARSE_4": "",
            "ERROR_PARSE_5": "",
            "ERROR_PARSE_6": "",
            "ERROR_PARSE_7": "",
            "ERROR_PARSE_8": "",
            "ERROR_PARSE_9": "",
            "ERROR_SIDAC_0": "Invalid simulation frequency selected",
            "ERROR_SIDAC_1": "Sensordistance can't be less then 1",
            "ERROR_SIDAC_10": "Conveyorbelt 1 already occupied",
            "ERROR_SIDAC_11": "Cannot drive conveyorbelt 1, rotationtable 1 is not in the right position",
            "ERROR_SIDAC_12": "Rotationtable 1 already occupied",
            "ERROR_SIDAC_13": "Cannot drive rotationtable 1, a workpiece would fall off",
            "ERROR_SIDAC_14": "Cannot rotate rotationtable 1 because there is a workpiece between conveyorbelt 1 and rotationtable 1",
            "ERROR_SIDAC_15": "Cannot rotate rotationtable 1 to conveyorbelt 2, because it is already at conveyorbelt 2",
            "ERROR_SIDAC_16": "Cannot rotate rotationtable 1 to conveyorbelt 1, because it is already at conveyorbelt 1",
            "ERROR_SIDAC_17": "Cannot rotate rotationtable 1 because there is a workpiece between rotationtable 1 and conveyorbelt 2",
            "ERROR_SIDAC_18": "Cannot rotate rotationtable 1 in both directions simultaneously",
            "ERROR_SIDAC_19": "Conveyorbelt 2 already occupied",
            "ERROR_SIDAC_2": "Undefined Outputvalue",
            "ERROR_SIDAC_20": "Cannot drive conveyorbelt 2, rotationtable 2 is not in the right position",
            "ERROR_SIDAC_21": "Rotationtable 2 already ocupied",
            "ERROR_SIDAC_22": "Cannot drive rotationtable 2, a workpiece would fall off",
            "ERROR_SIDAC_23": "Cannot rotate rotationtable 2 because there is a workpiece between conveyorbelt 2 and rotationtable 2",
            "ERROR_SIDAC_24": "Cannot rotate rotationtable 2 to conveyorbelt 3, because it is already at conveyorbelt 3",
            "ERROR_SIDAC_25": "Cannot rotate rotationtable 2 because there is a workpiece between rotationtable 2 and conveyorbelt 3",
            "ERROR_SIDAC_26": "Cannot rotate rotationtable 2 to conveyorbelt 3, because it is already at conveyorbelt 3",
            "ERROR_SIDAC_27": "Cannot rotate rotationtable 2 in both directions simultaneously",
            "ERROR_SIDAC_28": "Conveyorbelt 3 already occupied",
            "ERROR_SIDAC_29": "Cannot drive conveyorbelt 3, a workpiece would fall off",
            "ERROR_SIDAC_3": "Transporttable is already at conveyorbelt 1",
            "ERROR_SIDAC_30": "Transporttable already occupied",
            "ERROR_SIDAC_31": "Cannot move the milling machine to conveyorbelt 2, because it is already at conveyorbelt 2",
            "ERROR_SIDAC_32": "Cannot move the milling machine in both directions simultaneously",
            "ERROR_SIDAC_33": "Cannot move the milling machine further away from conveyorbelt 2",
            "ERROR_SIDAC_34": "Cannot raise the milling head any further",
            "ERROR_SIDAC_35": "Cannot move the milling head in both directions simultaneously",
            "ERROR_SIDAC_36": "Cannot lower the milling head any further",
            "ERROR_SIDAC_4": "Cannot move the transporttable to conveyorbelt 3, because there is a workpiece between the transporttable and conveyorbelt 1",
            "ERROR_SIDAC_5": "Cannot move the transporttable in both directions simultaneously",
            "ERROR_SIDAC_6": "Transporttable is already at conveyorbelt 1",
            "ERROR_SIDAC_7": "Cannot move the transporttable to conveyorbelt 1, because there is a workpiece between the transporttable and conveyorbelt 3",
            "ERROR_SIDAC_8": "Cannot drive the transporttable, a workpiece would fall off",
            "ERROR_SIDAC_9": "Cannot drive the transporttable in direction of conveyorbelt 1, because it isn't at conveyorbelt 1",
            "SIDAC_ANIMATION_CB1": "CB1",
            "SIDAC_ANIMATION_CB2": "CB2",
            "SIDAC_ANIMATION_CB3": "CB3",
            "SIDAC_ANIMATION_RT1": "RT1",
            "SIDAC_ANIMATION_RT2": "RT2",
            "SIDAC_ANIMATION_TT": "TT",
            "INPUTS_X0": "Transport table in line with conveyor belt 3 (low-active)",
            "INPUTS_X1": "Transport table in line with conveyor belt 1 (low-active)",
            "INPUTS_X10": "Turntable 2 - workpiece available",
            "INPUTS_X11": "Conveyor belt 3 - workpiece available",
            "INPUTS_X12": "Milling machine away from conveyor belt 2 (low-active)",
            "INPUTS_X13": "Milling machine at conveyor belt 2 (low-active)",
            "INPUTS_X14": "Milling head is up (low-active)",
            "INPUTS_X15": "Milling head is down (low-active)",
            "INPUTS_X16": "Emergency Stop",
            "INPUTS_X2": "Transport table - workpiece available",
            "INPUTS_X3": "Conveyor belt 1 - workpiece available",
            "INPUTS_X4": "Turntable 1 in line with conveyor belt 1 (low-active)",
            "INPUTS_X5": "Turntable 1 in line with conveyor belt 2 (low-active)",
            "INPUTS_X6": "Turntable 1 - workpiece available",
            "INPUTS_X7": "Conveyor belt 2 - workpiece available",
            "INPUTS_X8": "Turntable 2 in line with conveyor belt 2 (low-active)",
            "INPUTS_X9": "Turntable 2 in line with conveyor belt 3 (low-active)",
            "SIDAC_LOG_0": "",
            "SIDAC_LOG_1": "",
            "OUTPUTS_Y0": "Transport table - move to conveyor belt 3",
            "OUTPUTS_Y1": "Transport table - move to conveyor belt 1",
            "OUTPUTS_Y10": "Turntable 2 - rotate to conveyor belt 3",
            "OUTPUTS_Y11": "Turntable 2 - drive belt",
            "OUTPUTS_Y12": "Conveyor belt 3 - drive belt",
            "OUTPUTS_Y13": "Milling machine - approach conveyor belt 2",
            "OUTPUTS_Y14": "Milling machine - retreat from conveyor belt 2",
            "OUTPUTS_Y15": "Milling head - rise",
            "OUTPUTS_Y16": "Milling head -lower",
            "OUTPUTS_Y17": "Milling head - drive head",
            "OUTPUTS_Y2": "Transport table - drive conveyor belt similar to conveyor belt 1",
            "OUTPUTS_Y3": "Transport table - drive conveyor belt similar to conveyor belt 3",
            "OUTPUTS_Y4": "Conveyor belt 1 - drive belt",
            "OUTPUTS_Y5": "Turntable 1 - rotate to conveyor belt 1",
            "OUTPUTS_Y6": "Turntable 1 - rotate to conveyor belt 2",
            "OUTPUTS_Y7": "Turntable 1 - drive belt",
            "OUTPUTS_Y8": "Conveyor belt 2 - drive belt",
            "OUTPUTS_Y9": "Turntable 2 - rotate to conveyor belt 2",
        },
        "bg_BG": {
            "ECP_ADDMACHINE": "",
            "ECP_ADDMACHINEDIALOGUEINFORMATION": "",
            "ECP_CANCELBUTTON": "",
            "ECP_CLEARLOG": "",
            "ECP_CLOCKSPERSECONDUNIT": "",
            "ECP_CLOSEBUTTON": "",
            "ECP_CONNECT": "",
            "ECP_CONNECTING": "",
            "ECP_CONNECTIONREMAININGTIME": "",
            "ECP_CONNECTIONTOTALTIME": "",
            "ECP_CONTROLHEADER": "",
            "ECP_CURRENTINPUTVALUE": "",
            "ECP_CURRENTSTATE": "",
            "ECP_DELETEALLBUTTON": "",
            "ECP_DELETEMACHINE": "",
            "ECP_DELETEMACHINEDIALOGUEINFORMATION": "",
            "ECP_DISCONNECT": "",
            "ECP_DISCONNECTED": "",
            "ECP_DISCONNECTEDMESSAGE": "",
            "ECP_EQUATIONDEFINER": "",
            "ECP_EQUATIONSTABSINPUTS": "",
            "ECP_EQUATIONTABSHEADER": "",
            "ECP_EQUATIONTABSHSTAR": "",
            "ECP_EQUATIONTABSMACHINES": "",
            "ECP_EQUATIONTABSOUTPUTS": "",
            "ECP_ERRORLOG": "",
            "ECP_EXAMPLEBUTTON": "",
            "ECP_FILETRANSFERCOMPLETE": "",
            "ECP_INITIALIZE": "",
            "ECP_INITIALMODELSTATE": "",
            "ECP_INITSTATE": "",
            "ECP_INPUTDESCRIPTION": "",
            "ECP_LANGUAGES": "",
            "ECP_NAME": "",
            "ECP_NOFILESELECTED": "",
            "ECP_OKBUTTON": "",
            "ECP_ONLYSIMULATE": "",
            "ECP_OPENBUTTON": "",
            "ECP_OPTIONSBUTTON": "",
            "ECP_RESETSIMULATION": "",
            "ECP_SAVEBUTTON": "",
            "ECP_SAVEBUTTONLABEL": "",
            "ECP_SCENARIOEDITORDESCRIPTION": "",
            "ECP_SENSORDISTANCEUNIT": "",
            "ECP_SIMULATIONCLOCKSLIDER": "",
            "ECP_SIMULATIONSENSORSLIDER": "",
            "ECP_START": "",
            "ECP_STOP": "",
            "ECP_WEBCAMENABLED": "",
            "ECP_ZEQUATIONS": "",
            "ERROR_LAB_0": "",
            "ERROR_LAB_1": "",
            "ERROR_LAB_10": "",
            "ERROR_LAB_11": "",
            "ERROR_LAB_12": "",
            "ERROR_LAB_13": "",
            "ERROR_LAB_14": "",
            "ERROR_LAB_15": "",
            "ERROR_LAB_16": "",
            "ERROR_LAB_17": "",
            "ERROR_LAB_18": "",
            "ERROR_LAB_19": "",
            "ERROR_LAB_2": "",
            "ERROR_LAB_20": "",
            "ERROR_LAB_21": "",
            "ERROR_LAB_22": "",
            "ERROR_LAB_3": "",
            "ERROR_LAB_4": "",
            "ERROR_LAB_5": "",
            "ERROR_LAB_6": "",
            "ERROR_LAB_7": "",
            "ERROR_LAB_8": "",
            "ERROR_LAB_9": "",
            "ERROR_PARSE_0": "",
            "ERROR_PARSE_1": "",
            "ERROR_PARSE_10": "",
            "ERROR_PARSE_11": "",
            "ERROR_PARSE_12": "",
            "ERROR_PARSE_2": "",
            "ERROR_PARSE_23": "",
            "ERROR_PARSE_24": "",
            "ERROR_PARSE_25": "",
            "ERROR_PARSE_26": "",
            "ERROR_PARSE_3": "",
            "ERROR_PARSE_4": "",
            "ERROR_PARSE_5": "",
            "ERROR_PARSE_6": "",
            "ERROR_PARSE_7": "",
            "ERROR_PARSE_8": "",
            "ERROR_PARSE_9": "",
            "ERROR_SIDAC_0": "",
            "ERROR_SIDAC_1": "",
            "ERROR_SIDAC_10": "",
            "ERROR_SIDAC_11": "",
            "ERROR_SIDAC_12": "",
            "ERROR_SIDAC_13": "",
            "ERROR_SIDAC_14": "",
            "ERROR_SIDAC_15": "",
            "ERROR_SIDAC_16": "",
            "ERROR_SIDAC_17": "",
            "ERROR_SIDAC_18": "",
            "ERROR_SIDAC_19": "",
            "ERROR_SIDAC_2": "",
            "ERROR_SIDAC_20": "",
            "ERROR_SIDAC_21": "",
            "ERROR_SIDAC_22": "",
            "ERROR_SIDAC_23": "",
            "ERROR_SIDAC_24": "",
            "ERROR_SIDAC_25": "",
            "ERROR_SIDAC_26": "",
            "ERROR_SIDAC_27": "",
            "ERROR_SIDAC_28": "",
            "ERROR_SIDAC_29": "",
            "ERROR_SIDAC_3": "",
            "ERROR_SIDAC_30": "",
            "ERROR_SIDAC_31": "",
            "ERROR_SIDAC_32": "",
            "ERROR_SIDAC_33": "",
            "ERROR_SIDAC_34": "",
            "ERROR_SIDAC_35": "",
            "ERROR_SIDAC_36": "",
            "ERROR_SIDAC_4": "",
            "ERROR_SIDAC_5": "",
            "ERROR_SIDAC_6": "",
            "ERROR_SIDAC_7": "",
            "ERROR_SIDAC_8": "",
            "ERROR_SIDAC_9": "",
            "SIDAC_ANIMATION_CB1": "",
            "SIDAC_ANIMATION_CB2": "",
            "SIDAC_ANIMATION_CB3": "",
            "SIDAC_ANIMATION_RT1": "",
            "SIDAC_ANIMATION_RT2": "",
            "SIDAC_ANIMATION_TT": "",
            "INPUTS_X0": "",
            "INPUTS_X1": "",
            "INPUTS_X10": "",
            "INPUTS_X11": "",
            "INPUTS_X12": "",
            "INPUTS_X13": "",
            "INPUTS_X14": "",
            "INPUTS_X15": "",
            "INPUTS_X16": "",
            "INPUTS_X2": "",
            "INPUTS_X3": "",
            "INPUTS_X4": "",
            "INPUTS_X5": "",
            "INPUTS_X6": "",
            "INPUTS_X7": "",
            "INPUTS_X8": "",
            "INPUTS_X9": "",
            "SIDAC_LOG_0": "",
            "SIDAC_LOG_1": "",
            "OUTPUTS_Y0": "",
            "OUTPUTS_Y1": "",
            "OUTPUTS_Y10": "",
            "OUTPUTS_Y11": "",
            "OUTPUTS_Y12": "",
            "OUTPUTS_Y13": "",
            "OUTPUTS_Y14": "",
            "OUTPUTS_Y15": "",
            "OUTPUTS_Y16": "",
            "OUTPUTS_Y17": "",
            "OUTPUTS_Y2": "",
            "OUTPUTS_Y3": "",
            "OUTPUTS_Y4": "",
            "OUTPUTS_Y5": "",
            "OUTPUTS_Y6": "",
            "OUTPUTS_Y7": "",
            "OUTPUTS_Y8": "",
            "OUTPUTS_Y9": "",
        },
        "es_ES": {
            "ECP_ADDMACHINE": "",
            "ECP_ADDMACHINEDIALOGUEINFORMATION": "",
            "ECP_CANCELBUTTON": "",
            "ECP_CLEARLOG": "",
            "ECP_CLOCKSPERSECONDUNIT": "",
            "ECP_CLOSEBUTTON": "",
            "ECP_CONNECT": "",
            "ECP_CONNECTING": "",
            "ECP_CONNECTIONREMAININGTIME": "",
            "ECP_CONNECTIONTOTALTIME": "",
            "ECP_CONTROLHEADER": "",
            "ECP_CURRENTINPUTVALUE": "",
            "ECP_CURRENTSTATE": "",
            "ECP_DELETEALLBUTTON": "",
            "ECP_DELETEMACHINE": "",
            "ECP_DELETEMACHINEDIALOGUEINFORMATION": "",
            "ECP_DISCONNECT": "",
            "ECP_DISCONNECTED": "",
            "ECP_DISCONNECTEDMESSAGE": "",
            "ECP_EQUATIONDEFINER": "",
            "ECP_EQUATIONSTABSINPUTS": "",
            "ECP_EQUATIONTABSHEADER": "",
            "ECP_EQUATIONTABSHSTAR": "",
            "ECP_EQUATIONTABSMACHINES": "",
            "ECP_EQUATIONTABSOUTPUTS": "",
            "ECP_ERRORLOG": "",
            "ECP_EXAMPLEBUTTON": "",
            "ECP_FILETRANSFERCOMPLETE": "",
            "ECP_INITIALIZE": "",
            "ECP_INITIALMODELSTATE": "",
            "ECP_INITSTATE": "",
            "ECP_INPUTDESCRIPTION": "",
            "ECP_LANGUAGES": "",
            "ECP_NAME": "",
            "ECP_NOFILESELECTED": "",
            "ECP_OKBUTTON": "",
            "ECP_ONLYSIMULATE": "",
            "ECP_OPENBUTTON": "",
            "ECP_OPTIONSBUTTON": "",
            "ECP_RESETSIMULATION": "",
            "ECP_SAVEBUTTON": "",
            "ECP_SAVEBUTTONLABEL": "",
            "ECP_SCENARIOEDITORDESCRIPTION": "",
            "ECP_SENSORDISTANCEUNIT": "",
            "ECP_SIMULATIONCLOCKSLIDER": "",
            "ECP_SIMULATIONSENSORSLIDER": "",
            "ECP_START": "",
            "ECP_STOP": "",
            "ECP_WEBCAMENABLED": "",
            "ECP_ZEQUATIONS": "",
            "ERROR_LAB_0": "",
            "ERROR_LAB_1": "",
            "ERROR_LAB_10": "",
            "ERROR_LAB_11": "",
            "ERROR_LAB_12": "",
            "ERROR_LAB_13": "",
            "ERROR_LAB_14": "",
            "ERROR_LAB_15": "",
            "ERROR_LAB_16": "",
            "ERROR_LAB_17": "",
            "ERROR_LAB_18": "",
            "ERROR_LAB_19": "",
            "ERROR_LAB_2": "",
            "ERROR_LAB_20": "",
            "ERROR_LAB_21": "",
            "ERROR_LAB_22": "",
            "ERROR_LAB_3": "",
            "ERROR_LAB_4": "",
            "ERROR_LAB_5": "",
            "ERROR_LAB_6": "",
            "ERROR_LAB_7": "",
            "ERROR_LAB_8": "",
            "ERROR_LAB_9": "",
            "ERROR_PARSE_0": "",
            "ERROR_PARSE_1": "",
            "ERROR_PARSE_10": "",
            "ERROR_PARSE_11": "",
            "ERROR_PARSE_12": "",
            "ERROR_PARSE_2": "",
            "ERROR_PARSE_23": "",
            "ERROR_PARSE_24": "",
            "ERROR_PARSE_25": "",
            "ERROR_PARSE_26": "",
            "ERROR_PARSE_3": "",
            "ERROR_PARSE_4": "",
            "ERROR_PARSE_5": "",
            "ERROR_PARSE_6": "",
            "ERROR_PARSE_7": "",
            "ERROR_PARSE_8": "",
            "ERROR_PARSE_9": "",
            "ERROR_SIDAC_0": "",
            "ERROR_SIDAC_1": "",
            "ERROR_SIDAC_10": "",
            "ERROR_SIDAC_11": "",
            "ERROR_SIDAC_12": "",
            "ERROR_SIDAC_13": "",
            "ERROR_SIDAC_14": "",
            "ERROR_SIDAC_15": "",
            "ERROR_SIDAC_16": "",
            "ERROR_SIDAC_17": "",
            "ERROR_SIDAC_18": "",
            "ERROR_SIDAC_19": "",
            "ERROR_SIDAC_2": "",
            "ERROR_SIDAC_20": "",
            "ERROR_SIDAC_21": "",
            "ERROR_SIDAC_22": "",
            "ERROR_SIDAC_23": "",
            "ERROR_SIDAC_24": "",
            "ERROR_SIDAC_25": "",
            "ERROR_SIDAC_26": "",
            "ERROR_SIDAC_27": "",
            "ERROR_SIDAC_28": "",
            "ERROR_SIDAC_29": "",
            "ERROR_SIDAC_3": "",
            "ERROR_SIDAC_30": "",
            "ERROR_SIDAC_31": "",
            "ERROR_SIDAC_32": "",
            "ERROR_SIDAC_33": "",
            "ERROR_SIDAC_34": "",
            "ERROR_SIDAC_35": "",
            "ERROR_SIDAC_36": "",
            "ERROR_SIDAC_4": "",
            "ERROR_SIDAC_5": "",
            "ERROR_SIDAC_6": "",
            "ERROR_SIDAC_7": "",
            "ERROR_SIDAC_8": "",
            "ERROR_SIDAC_9": "",
            "SIDAC_ANIMATION_CB1": "",
            "SIDAC_ANIMATION_CB2": "",
            "SIDAC_ANIMATION_CB3": "",
            "SIDAC_ANIMATION_RT1": "",
            "SIDAC_ANIMATION_RT2": "",
            "SIDAC_ANIMATION_TT": "",
            "INPUTS_X0": "",
            "INPUTS_X1": "",
            "INPUTS_X10": "",
            "INPUTS_X11": "",
            "INPUTS_X12": "",
            "INPUTS_X13": "",
            "INPUTS_X14": "",
            "INPUTS_X15": "",
            "INPUTS_X16": "",
            "INPUTS_X2": "",
            "INPUTS_X3": "",
            "INPUTS_X4": "",
            "INPUTS_X5": "",
            "INPUTS_X6": "",
            "INPUTS_X7": "",
            "INPUTS_X8": "",
            "INPUTS_X9": "",
            "SIDAC_LOG_0": "",
            "SIDAC_LOG_1": "",
            "OUTPUTS_Y0": "",
            "OUTPUTS_Y1": "",
            "OUTPUTS_Y10": "",
            "OUTPUTS_Y11": "",
            "OUTPUTS_Y12": "",
            "OUTPUTS_Y13": "",
            "OUTPUTS_Y14": "",
            "OUTPUTS_Y15": "",
            "OUTPUTS_Y16": "",
            "OUTPUTS_Y17": "",
            "OUTPUTS_Y2": "",
            "OUTPUTS_Y3": "",
            "OUTPUTS_Y4": "",
            "OUTPUTS_Y5": "",
            "OUTPUTS_Y6": "",
            "OUTPUTS_Y7": "",
            "OUTPUTS_Y8": "",
            "OUTPUTS_Y9": "",
        },
        "uk_UA": {
            "ECP_ADDMACHINE": "",
            "ECP_ADDMACHINEDIALOGUEINFORMATION": "",
            "ECP_CANCELBUTTON": "",
            "ECP_CLEARLOG": "",
            "ECP_CLOCKSPERSECONDUNIT": "",
            "ECP_CLOSEBUTTON": "",
            "ECP_CONNECT": "",
            "ECP_CONNECTING": "",
            "ECP_CONNECTIONREMAININGTIME": "",
            "ECP_CONNECTIONTOTALTIME": "",
            "ECP_CONTROLHEADER": "",
            "ECP_CURRENTINPUTVALUE": "",
            "ECP_CURRENTSTATE": "",
            "ECP_DELETEALLBUTTON": "",
            "ECP_DELETEMACHINE": "",
            "ECP_DELETEMACHINEDIALOGUEINFORMATION": "",
            "ECP_DISCONNECT": "",
            "ECP_DISCONNECTED": "",
            "ECP_DISCONNECTEDMESSAGE": "",
            "ECP_EQUATIONDEFINER": "",
            "ECP_EQUATIONSTABSINPUTS": "",
            "ECP_EQUATIONTABSHEADER": "",
            "ECP_EQUATIONTABSHSTAR": "",
            "ECP_EQUATIONTABSMACHINES": "",
            "ECP_EQUATIONTABSOUTPUTS": "",
            "ECP_ERRORLOG": "",
            "ECP_EXAMPLEBUTTON": "",
            "ECP_FILETRANSFERCOMPLETE": "",
            "ECP_INITIALIZE": "",
            "ECP_INITIALMODELSTATE": "",
            "ECP_INITSTATE": "",
            "ECP_INPUTDESCRIPTION": "",
            "ECP_LANGUAGES": "",
            "ECP_NAME": "",
            "ECP_NOFILESELECTED": "",
            "ECP_OKBUTTON": "",
            "ECP_ONLYSIMULATE": "",
            "ECP_OPENBUTTON": "",
            "ECP_OPTIONSBUTTON": "",
            "ECP_RESETSIMULATION": "",
            "ECP_SAVEBUTTON": "",
            "ECP_SAVEBUTTONLABEL": "",
            "ECP_SCENARIOEDITORDESCRIPTION": "",
            "ECP_SENSORDISTANCEUNIT": "",
            "ECP_SIMULATIONCLOCKSLIDER": "",
            "ECP_SIMULATIONSENSORSLIDER": "",
            "ECP_START": "",
            "ECP_STOP": "",
            "ECP_WEBCAMENABLED": "",
            "ECP_ZEQUATIONS": "",
            "ERROR_LAB_0": "",
            "ERROR_LAB_1": "",
            "ERROR_LAB_10": "",
            "ERROR_LAB_11": "",
            "ERROR_LAB_12": "",
            "ERROR_LAB_13": "",
            "ERROR_LAB_14": "",
            "ERROR_LAB_15": "",
            "ERROR_LAB_16": "",
            "ERROR_LAB_17": "",
            "ERROR_LAB_18": "",
            "ERROR_LAB_19": "",
            "ERROR_LAB_2": "",
            "ERROR_LAB_20": "",
            "ERROR_LAB_21": "",
            "ERROR_LAB_22": "",
            "ERROR_LAB_3": "",
            "ERROR_LAB_4": "",
            "ERROR_LAB_5": "",
            "ERROR_LAB_6": "",
            "ERROR_LAB_7": "",
            "ERROR_LAB_8": "",
            "ERROR_LAB_9": "",
            "ERROR_PARSE_0": "",
            "ERROR_PARSE_1": "",
            "ERROR_PARSE_10": "",
            "ERROR_PARSE_11": "",
            "ERROR_PARSE_12": "",
            "ERROR_PARSE_2": "",
            "ERROR_PARSE_23": "",
            "ERROR_PARSE_24": "",
            "ERROR_PARSE_25": "",
            "ERROR_PARSE_26": "",
            "ERROR_PARSE_3": "",
            "ERROR_PARSE_4": "",
            "ERROR_PARSE_5": "",
            "ERROR_PARSE_6": "",
            "ERROR_PARSE_7": "",
            "ERROR_PARSE_8": "",
            "ERROR_PARSE_9": "",
            "ERROR_SIDAC_0": "",
            "ERROR_SIDAC_1": "",
            "ERROR_SIDAC_10": "",
            "ERROR_SIDAC_11": "",
            "ERROR_SIDAC_12": "",
            "ERROR_SIDAC_13": "",
            "ERROR_SIDAC_14": "",
            "ERROR_SIDAC_15": "",
            "ERROR_SIDAC_16": "",
            "ERROR_SIDAC_17": "",
            "ERROR_SIDAC_18": "",
            "ERROR_SIDAC_19": "",
            "ERROR_SIDAC_2": "",
            "ERROR_SIDAC_20": "",
            "ERROR_SIDAC_21": "",
            "ERROR_SIDAC_22": "",
            "ERROR_SIDAC_23": "",
            "ERROR_SIDAC_24": "",
            "ERROR_SIDAC_25": "",
            "ERROR_SIDAC_26": "",
            "ERROR_SIDAC_27": "",
            "ERROR_SIDAC_28": "",
            "ERROR_SIDAC_29": "",
            "ERROR_SIDAC_3": "",
            "ERROR_SIDAC_30": "",
            "ERROR_SIDAC_31": "",
            "ERROR_SIDAC_32": "",
            "ERROR_SIDAC_33": "",
            "ERROR_SIDAC_34": "",
            "ERROR_SIDAC_35": "",
            "ERROR_SIDAC_36": "",
            "ERROR_SIDAC_4": "",
            "ERROR_SIDAC_5": "",
            "ERROR_SIDAC_6": "",
            "ERROR_SIDAC_7": "",
            "ERROR_SIDAC_8": "",
            "ERROR_SIDAC_9": "",
            "SIDAC_ANIMATION_CB1": "",
            "SIDAC_ANIMATION_CB2": "",
            "SIDAC_ANIMATION_CB3": "",
            "SIDAC_ANIMATION_RT1": "",
            "SIDAC_ANIMATION_RT2": "",
            "SIDAC_ANIMATION_TT": "",
            "INPUTS_X0": "",
            "INPUTS_X1": "",
            "INPUTS_X10": "",
            "INPUTS_X11": "",
            "INPUTS_X12": "",
            "INPUTS_X13": "",
            "INPUTS_X14": "",
            "INPUTS_X15": "",
            "INPUTS_X16": "",
            "INPUTS_X2": "",
            "INPUTS_X3": "",
            "INPUTS_X4": "",
            "INPUTS_X5": "",
            "INPUTS_X6": "",
            "INPUTS_X7": "",
            "INPUTS_X8": "",
            "INPUTS_X9": "",
            "SIDAC_LOG_0": "",
            "SIDAC_LOG_1": "",
            "OUTPUTS_Y0": "",
            "OUTPUTS_Y1": "",
            "OUTPUTS_Y10": "",
            "OUTPUTS_Y11": "",
            "OUTPUTS_Y12": "",
            "OUTPUTS_Y13": "",
            "OUTPUTS_Y14": "",
            "OUTPUTS_Y15": "",
            "OUTPUTS_Y16": "",
            "OUTPUTS_Y17": "",
            "OUTPUTS_Y2": "",
            "OUTPUTS_Y3": "",
            "OUTPUTS_Y4": "",
            "OUTPUTS_Y5": "",
            "OUTPUTS_Y6": "",
            "OUTPUTS_Y7": "",
            "OUTPUTS_Y8": "",
            "OUTPUTS_Y9": "",
        },
        "ru_RU": {
            "ECP_ADDMACHINE": "",
            "ECP_ADDMACHINEDIALOGUEINFORMATION": "",
            "ECP_CANCELBUTTON": "",
            "ECP_CLEARLOG": "",
            "ECP_CLOCKSPERSECONDUNIT": "",
            "ECP_CLOSEBUTTON": "",
            "ECP_CONNECT": "",
            "ECP_CONNECTING": "",
            "ECP_CONNECTIONREMAININGTIME": "",
            "ECP_CONNECTIONTOTALTIME": "",
            "ECP_CONTROLHEADER": "",
            "ECP_CURRENTINPUTVALUE": "",
            "ECP_CURRENTSTATE": "",
            "ECP_DELETEALLBUTTON": "",
            "ECP_DELETEMACHINE": "",
            "ECP_DELETEMACHINEDIALOGUEINFORMATION": "",
            "ECP_DISCONNECT": "",
            "ECP_DISCONNECTED": "",
            "ECP_DISCONNECTEDMESSAGE": "",
            "ECP_EQUATIONDEFINER": "",
            "ECP_EQUATIONSTABSINPUTS": "",
            "ECP_EQUATIONTABSHEADER": "",
            "ECP_EQUATIONTABSHSTAR": "",
            "ECP_EQUATIONTABSMACHINES": "",
            "ECP_EQUATIONTABSOUTPUTS": "",
            "ECP_ERRORLOG": "",
            "ECP_EXAMPLEBUTTON": "",
            "ECP_FILETRANSFERCOMPLETE": "",
            "ECP_INITIALIZE": "",
            "ECP_INITIALMODELSTATE": "",
            "ECP_INITSTATE": "",
            "ECP_INPUTDESCRIPTION": "",
            "ECP_LANGUAGES": "",
            "ECP_NAME": "",
            "ECP_NOFILESELECTED": "",
            "ECP_OKBUTTON": "",
            "ECP_ONLYSIMULATE": "",
            "ECP_OPENBUTTON": "",
            "ECP_OPTIONSBUTTON": "",
            "ECP_RESETSIMULATION": "",
            "ECP_SAVEBUTTON": "",
            "ECP_SAVEBUTTONLABEL": "",
            "ECP_SCENARIOEDITORDESCRIPTION": "",
            "ECP_SENSORDISTANCEUNIT": "",
            "ECP_SIMULATIONCLOCKSLIDER": "",
            "ECP_SIMULATIONSENSORSLIDER": "",
            "ECP_START": "",
            "ECP_STOP": "",
            "ECP_WEBCAMENABLED": "",
            "ECP_ZEQUATIONS": "",
            "ERROR_LAB_0": "",
            "ERROR_LAB_1": "",
            "ERROR_LAB_10": "",
            "ERROR_LAB_11": "",
            "ERROR_LAB_12": "",
            "ERROR_LAB_13": "",
            "ERROR_LAB_14": "",
            "ERROR_LAB_15": "",
            "ERROR_LAB_16": "",
            "ERROR_LAB_17": "",
            "ERROR_LAB_18": "",
            "ERROR_LAB_19": "",
            "ERROR_LAB_2": "",
            "ERROR_LAB_20": "",
            "ERROR_LAB_21": "",
            "ERROR_LAB_22": "",
            "ERROR_LAB_3": "",
            "ERROR_LAB_4": "",
            "ERROR_LAB_5": "",
            "ERROR_LAB_6": "",
            "ERROR_LAB_7": "",
            "ERROR_LAB_8": "",
            "ERROR_LAB_9": "",
            "ERROR_PARSE_0": "",
            "ERROR_PARSE_1": "",
            "ERROR_PARSE_10": "",
            "ERROR_PARSE_11": "",
            "ERROR_PARSE_12": "",
            "ERROR_PARSE_2": "",
            "ERROR_PARSE_23": "",
            "ERROR_PARSE_24": "",
            "ERROR_PARSE_25": "",
            "ERROR_PARSE_26": "",
            "ERROR_PARSE_3": "",
            "ERROR_PARSE_4": "",
            "ERROR_PARSE_5": "",
            "ERROR_PARSE_6": "",
            "ERROR_PARSE_7": "",
            "ERROR_PARSE_8": "",
            "ERROR_PARSE_9": "",
            "ERROR_SIDAC_0": "",
            "ERROR_SIDAC_1": "",
            "ERROR_SIDAC_10": "",
            "ERROR_SIDAC_11": "",
            "ERROR_SIDAC_12": "",
            "ERROR_SIDAC_13": "",
            "ERROR_SIDAC_14": "",
            "ERROR_SIDAC_15": "",
            "ERROR_SIDAC_16": "",
            "ERROR_SIDAC_17": "",
            "ERROR_SIDAC_18": "",
            "ERROR_SIDAC_19": "",
            "ERROR_SIDAC_2": "",
            "ERROR_SIDAC_20": "",
            "ERROR_SIDAC_21": "",
            "ERROR_SIDAC_22": "",
            "ERROR_SIDAC_23": "",
            "ERROR_SIDAC_24": "",
            "ERROR_SIDAC_25": "",
            "ERROR_SIDAC_26": "",
            "ERROR_SIDAC_27": "",
            "ERROR_SIDAC_28": "",
            "ERROR_SIDAC_29": "",
            "ERROR_SIDAC_3": "",
            "ERROR_SIDAC_30": "",
            "ERROR_SIDAC_31": "",
            "ERROR_SIDAC_32": "",
            "ERROR_SIDAC_33": "",
            "ERROR_SIDAC_34": "",
            "ERROR_SIDAC_35": "",
            "ERROR_SIDAC_36": "",
            "ERROR_SIDAC_4": "",
            "ERROR_SIDAC_5": "",
            "ERROR_SIDAC_6": "",
            "ERROR_SIDAC_7": "",
            "ERROR_SIDAC_8": "",
            "ERROR_SIDAC_9": "",
            "SIDAC_ANIMATION_CB1": "",
            "SIDAC_ANIMATION_CB2": "",
            "SIDAC_ANIMATION_CB3": "",
            "SIDAC_ANIMATION_RT1": "",
            "SIDAC_ANIMATION_RT2": "",
            "SIDAC_ANIMATION_TT": "",
            "INPUTS_X0": "",
            "INPUTS_X1": "",
            "INPUTS_X10": "",
            "INPUTS_X11": "",
            "INPUTS_X12": "",
            "INPUTS_X13": "",
            "INPUTS_X14": "",
            "INPUTS_X15": "",
            "INPUTS_X16": "",
            "INPUTS_X2": "",
            "INPUTS_X3": "",
            "INPUTS_X4": "",
            "INPUTS_X5": "",
            "INPUTS_X6": "",
            "INPUTS_X7": "",
            "INPUTS_X8": "",
            "INPUTS_X9": "",
            "SIDAC_LOG_0": "",
            "SIDAC_LOG_1": "",
            "OUTPUTS_Y0": "",
            "OUTPUTS_Y1": "",
            "OUTPUTS_Y10": "",
            "OUTPUTS_Y11": "",
            "OUTPUTS_Y12": "",
            "OUTPUTS_Y13": "",
            "OUTPUTS_Y14": "",
            "OUTPUTS_Y15": "",
            "OUTPUTS_Y16": "",
            "OUTPUTS_Y17": "",
            "OUTPUTS_Y2": "",
            "OUTPUTS_Y3": "",
            "OUTPUTS_Y4": "",
            "OUTPUTS_Y5": "",
            "OUTPUTS_Y6": "",
            "OUTPUTS_Y7": "",
            "OUTPUTS_Y8": "",
            "OUTPUTS_Y9": "",
        }
    }
}